Traceback (most recent call last):
  File "/home/motoyo/motoyohosting/authsysproject/settings.py", line 25, in <module>
    SECRET_KEY = os.environ["SECRET_KEY"]
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'SECRET_KEY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/motoyo/motoyohosting/manage.py", line 22, in <module>
    main()
  File "/home/motoyo/motoyohosting/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/motoyo/motoyohosting/authsysproject/settings.py", line 27, in <module>
    raise RuntimeError("Could not find a SECRET_KEY in environment") from e
RuntimeError: Could not find a SECRET_KEY in environment
Traceback (most recent call last):
  File "/home/motoyo/motoyohosting/authsysproject/settings.py", line 25, in <module>
    SECRET_KEY = os.environ["SECRET_KEY"]
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'SECRET_KEY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/motoyo/motoyohosting/manage.py", line 22, in <module>
    main()
  File "/home/motoyo/motoyohosting/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/motoyo/motoyohosting/authsysproject/settings.py", line 27, in <module>
    raise RuntimeError("Could not find a SECRET_KEY in environment") from e
RuntimeError: Could not find a SECRET_KEY in environment
Traceback (most recent call last):
  File "/home/motoyo/motoyohosting/authsysproject/settings.py", line 25, in <module>
    SECRET_KEY = os.environ["SECRET_KEY"]
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'SECRET_KEY'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/motoyo/motoyohosting/manage.py", line 22, in <module>
    main()
  File "/home/motoyo/motoyohosting/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/motoyo/motoyohosting/authsysproject/settings.py", line 27, in <module>
    raise RuntimeError("Could not find a SECRET_KEY in environment") from e
RuntimeError: Could not find a SECRET_KEY in environment
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
May 29, 2023 - 17:06:31
Django version 4.2, using settings 'authsysproject.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Session data corrupted
[29/May/2023 17:06:55] "GET / HTTP/1.0" 200 3990
[29/May/2023 17:06:55] "GET /static/users/images/LOGO%20MTY.png HTTP/1.0" 304 0
[29/May/2023 17:06:56] "GET /static/users/css/main.css HTTP/1.0" 304 0
[29/May/2023 17:06:56] "GET /static/users/images/background.jpg HTTP/1.0" 304 0
Session data corrupted
[29/May/2023 17:06:58] "GET / HTTP/1.0" 200 3990
Session data corrupted
[29/May/2023 17:06:59] "GET /about/ HTTP/1.0" 200 12955
[29/May/2023 17:06:59] "GET /static/users/images/about-img.png HTTP/1.0" 304 0
[29/May/2023 17:06:59] "GET /static/users/images/team-1.png HTTP/1.0" 304 0
[29/May/2023 17:06:59] "GET /static/users/images/team-2.png HTTP/1.0" 304 0
[29/May/2023 17:06:59] "GET /static/users/images/team-3.png HTTP/1.0" 304 0
Session data corrupted
[29/May/2023 17:07:00] "GET /hosting/ HTTP/1.0" 200 5015
Session data corrupted
[29/May/2023 17:07:03] "GET /login/ HTTP/1.0" 200 5129
Session data corrupted
[29/May/2023 17:07:05] "POST /login/ HTTP/1.0" 302 0
[29/May/2023 17:07:05] "GET / HTTP/1.0" 200 3972
[29/May/2023 17:07:17] "GET / HTTP/1.0" 200 3972
[29/May/2023 17:07:18] "GET /about/ HTTP/1.0" 200 12937
[29/May/2023 17:07:19] "GET /hosting/ HTTP/1.0" 200 4997
[29/May/2023 20:59:36] "GET / HTTP/1.0" 200 3972
[29/May/2023 20:59:36] "GET /static/users/css/main.css HTTP/1.0" 200 3459
[29/May/2023 20:59:36] "GET /static/users/images/LOGO%20MTY.png HTTP/1.0" 304 0
[29/May/2023 20:59:36] "GET /static/users/images/background.jpg HTTP/1.0" 304 0
[29/May/2023 20:59:38] "GET /about/ HTTP/1.0" 200 12937
[29/May/2023 20:59:38] "GET /static/users/images/about-img.png HTTP/1.0" 304 0
[29/May/2023 20:59:38] "GET /static/users/images/team-1.png HTTP/1.0" 304 0
[29/May/2023 20:59:38] "GET /static/users/images/team-2.png HTTP/1.0" 304 0
[29/May/2023 20:59:38] "GET /static/users/images/team-3.png HTTP/1.0" 304 0
[30/May/2023 06:11:35] "GET / HTTP/1.0" 200 3972
[30/May/2023 06:11:35] "GET /static/users/css/main.css HTTP/1.0" 304 0
[30/May/2023 06:11:35] "GET /static/users/images/LOGO%20MTY.png HTTP/1.0" 304 0
[30/May/2023 06:11:35] "GET /static/users/images/background.jpg HTTP/1.0" 304 0
[30/May/2023 06:11:39] "GET / HTTP/1.0" 200 3972
[30/May/2023 06:11:41] "GET /about/ HTTP/1.0" 200 12937
[30/May/2023 06:11:41] "GET /static/users/images/about-img.png HTTP/1.0" 304 0
[30/May/2023 06:11:41] "GET /static/users/images/team-1.png HTTP/1.0" 304 0
[30/May/2023 06:11:41] "GET /static/users/images/team-3.png HTTP/1.0" 304 0
[30/May/2023 06:11:41] "GET /static/users/images/team-2.png HTTP/1.0" 304 0
[30/May/2023 06:11:44] "GET / HTTP/1.0" 200 3972
[30/May/2023 07:14:49] "GET /hosting/ HTTP/1.0" 200 4997
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
[30/May/2023 07:15:20] "POST /hosting/ HTTP/1.0" 200 4997
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
[30/May/2023 07:18:46] "POST /hosting/ HTTP/1.0" 200 5311
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/urllib3/connectionpool.py:1095: InsecureRequestWarning: Unverified HTTPS request is being made to host '172.26.51.0'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
[30/May/2023 07:19:58] "POST /hosting/ HTTP/1.0" 200 5223
[30/May/2023 07:39:23] "GET / HTTP/1.0" 200 3972
[30/May/2023 07:39:56] "GET /about/ HTTP/1.0" 200 12937
[30/May/2023 07:40:25] "GET /logout/ HTTP/1.0" 200 3652
[30/May/2023 07:40:27] "GET /login/ HTTP/1.0" 200 5129
[30/May/2023 07:40:41] "GET /register/ HTTP/1.0" 200 6051
[30/May/2023 07:46:41] "GET /hosting/ HTTP/1.0" 200 5015
[30/May/2023 07:46:55] "GET /login/ HTTP/1.0" 200 5129
Invalid HTTP_HOST header: '172.26.51.5'. You may need to add '172.26.51.5' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.26.51.5'. You may need to add '172.26.51.5' to ALLOWED_HOSTS.
Bad Request: /
[30/May/2023 08:27:43] "GET / HTTP/1.0" 400 66786
Invalid HTTP_HOST header: '172.26.51.5'. You may need to add '172.26.51.5' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.26.51.5'. You may need to add '172.26.51.5' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[30/May/2023 08:27:44] "GET /favicon.ico HTTP/1.0" 400 66490
Invalid HTTP_HOST header: '172.26.51.5'. You may need to add '172.26.51.5' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.26.51.5'. You may need to add '172.26.51.5' to ALLOWED_HOSTS.
Bad Request: /
[30/May/2023 08:29:03] "GET / HTTP/1.0" 400 66649
Invalid HTTP_HOST header: '172.26.51.5'. You may need to add '172.26.51.5' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.26.51.5'. You may need to add '172.26.51.5' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[30/May/2023 08:29:04] "GET /favicon.ico HTTP/1.0" 400 66490
[30/May/2023 09:55:52] "GET / HTTP/1.0" 200 3990
[30/May/2023 09:55:52] "GET /static/users/css/main.css HTTP/1.0" 200 3459
[30/May/2023 09:55:52] "GET /static/users/images/LOGO%20MTY.png HTTP/1.0" 200 2883
[30/May/2023 09:55:52] "GET /static/users/images/background.jpg HTTP/1.0" 200 457987
Not Found: /favicon.ico
[30/May/2023 09:55:52] "GET /favicon.ico HTTP/1.0" 404 3302
[30/May/2023 09:55:59] "GET / HTTP/1.0" 200 3990
[30/May/2023 09:56:02] "GET /about/ HTTP/1.0" 200 12955
[30/May/2023 09:56:02] "GET /static/users/images/about-img.png HTTP/1.0" 200 144014
[30/May/2023 09:56:02] "GET /static/users/images/team-1.png HTTP/1.0" 200 127976
[30/May/2023 09:56:02] "GET /static/users/images/team-2.png HTTP/1.0" 200 282499
[30/May/2023 09:56:02] "GET /static/users/images/team-3.png HTTP/1.0" 200 469518
[30/May/2023 09:56:10] "GET /hosting/ HTTP/1.0" 200 5015
Invalid HTTP_HOST header: '172.26.51.5'. You may need to add '172.26.51.5' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.26.51.5'. You may need to add '172.26.51.5' to ALLOWED_HOSTS.
Bad Request: /
[30/May/2023 11:32:14] "GET / HTTP/1.0" 400 66798
Invalid HTTP_HOST header: '172.26.51.5'. You may need to add '172.26.51.5' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/motoyo/motoyohosting/env/lib/python3.10/site-packages/django/http/request.py", line 167, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '172.26.51.5'. You may need to add '172.26.51.5' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[30/May/2023 11:32:14] "GET /favicon.ico HTTP/1.0" 400 66502
[02/Jun/2023 07:34:00] "GET / HTTP/1.0" 200 3990
[02/Jun/2023 07:34:00] "GET /static/users/css/main.css HTTP/1.0" 304 0
[02/Jun/2023 07:34:01] "GET /static/users/images/LOGO%20MTY.png HTTP/1.0" 304 0
[02/Jun/2023 07:34:01] "GET /static/users/images/background.jpg HTTP/1.0" 304 0
[02/Jun/2023 07:34:05] "GET /login/ HTTP/1.0" 200 5129
[02/Jun/2023 07:34:07] "POST /login/ HTTP/1.0" 302 0
[02/Jun/2023 07:34:07] "GET / HTTP/1.0" 200 3972
[02/Jun/2023 07:34:09] "GET /hosting/ HTTP/1.0" 200 4997
[02/Jun/2023 07:34:13] "GET /about/ HTTP/1.0" 200 12937
[02/Jun/2023 07:34:13] "GET /static/users/images/about-img.png HTTP/1.0" 304 0
[02/Jun/2023 07:34:13] "GET /static/users/images/team-2.png HTTP/1.0" 304 0
[02/Jun/2023 07:34:13] "GET /static/users/images/team-1.png HTTP/1.0" 200 127976
[02/Jun/2023 07:34:13] "GET /static/users/images/team-3.png HTTP/1.0" 304 0
[02/Jun/2023 07:34:14] "GET / HTTP/1.0" 200 3972
[02/Jun/2023 07:34:16] "GET /about/ HTTP/1.0" 200 12937
[02/Jun/2023 07:34:17] "GET /profile/ HTTP/1.0" 200 3604
[02/Jun/2023 07:34:44] "GET / HTTP/1.0" 200 3972
[02/Jun/2023 07:34:46] "GET /about/ HTTP/1.0" 200 12937
[02/Jun/2023 07:37:19] "GET / HTTP/1.0" 200 3990
